layout_spectrum: 0.9523966
typography_spectrum: 0.007986295
color:
  saturation: 0.3180402
  lightness: 0.5090268
  brandStrength: 0.750738
  rhythmicContrast: 0.01359399
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: 'Munish '
